fix currency plugin

diff --git a/currency/currency b/currency/currency
--- a/currency/currency
+++ b/currency/currency
@@ -1,49 +1,62 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # Author: Alexander Epstein https://github.com/alexanderepstein
+# Expanded: Rohit Goswami https://github.com/HaoZeke
 
-base=""
-exchangeTo=""
-currentVersion="1.13.0"
-configuredClient=""
+unset base
+unset exchangeTo
+currentVersion="1.23.0"
+unset configuredClient
+currencyCodes=(AUD BAM BGN BMD BND BRL CAD CHF CNY CZK DJF DKK
+  EUR GBP HKD HRK HUF IDR ISK ILS INR
+  JPY KRW MXN MYR NOK NZD PAB PHP PLN
+  RON RUB SEK SGD THB TRY USD ZAR)
 
-## This function determines which http get tool the system has installed and returns an error if there isnt one
-getConfiguredClient()
-{
-    if  command -v curl &>/dev/null ; then
+  ## This function determines which http get tool the system has installed and returns an error if there isnt one
+  getConfiguredClient()
+  {
+    if command -v curl &>/dev/null; then
       configuredClient="curl"
-    elif command -v wget &>/dev/null ; then
+    elif command -v wget &>/dev/null; then
       configuredClient="wget"
-    elif command -v fetch &>/dev/null ; then
+    elif command -v http &>/dev/null; then
+      configuredClient="httpie"
+    elif command -v fetch &>/dev/null; then
       configuredClient="fetch"
     else
-      echo "Error: This tool reqires either curl, wget, or fetch to be installed."
+      echo "Error: This tool requires either curl, wget, httpie or fetch to be installed." >&2
       return 1
     fi
+  }
 
-}
+  peggedTo()
+  {
+    case "$@" in
+      BAM)  echo "EUR:1.95583" ;;
+      BMD)  echo "USD:1.0" ;;
+      BND)  echo "SGD:1.0" ;;
+      DJF)  echo "USD:177.721" ;;
+      PAB)  echo "USD:1.0" ;;
+      *)    echo "1" ;;
+    esac
+  }
 
-## Allows to call the users configured client without if statements everywhere
-httpGet()
-{
-  case "$configuredClient" in
-    curl) curl -A curl -s "$@";;
-    wget) wget -qO- "$@";;
-    fetch) fetch -o "...";;
-  esac
-}
+  ## Allows to call the users configured client without if statements everywhere
+  httpGet()
+  {
+    case "$configuredClient" in
+      curl)  curl -A curl -s "$@" ;;
+      wget)  wget -qO- "$@" ;;
+      httpie) http -b GET "$@" ;;
+      fetch) fetch -q "$@" ;;
+    esac
+  }
 
 checkValidCurrency()
 {
-  if [[ $1 != "AUD" && $1 != "BGN" && $1 != "BRL" \
-      && $1 != "CAD" && $1 != "CHF" && $1 != "CNY" && $1 != "CZK" && $1 != "DKK" \
-      && $1 != "EUR" && $1 != "GBP" && $1 != "HKD" && $1 != "HRK" && $1 != "HUF" \
-      && $1 != "IDR" && $1 != "ILS" && $1 != "INR" && $1 != "JPY" && $1 != "KRW" \
-      && $1 != "MXN" && $1 != "MYR" && $1 != "NOK" && $1 != "NZD" && $1 != "PHP" \
-      && $1 != "PLN" && $1 != "RON" && $1 != "RUB" && $1 != "SEK" && $1 != "SGD" \
-    && $1 != "THB" && $1 != "TRY" && $1 != "USD" && $1 != "ZAR" ]];then
-    echo "1"
-  else
+  if [[ "${currencyCodes[*]}" == *"$(echo "${@}" | tr -d '[:space:]')"* ]]; then
     echo "0"
+  else
+    echo "1"
   fi
 }
 
@@ -54,19 +67,20 @@ getBase()
   echo -n "What is the base currency: "
   read -r base
   base=$(echo $base | tr /a-z/ /A-Z/)
-  if [[ $(checkValidCurrency $base) == "1"  ]];then
+  if [[ $(checkValidCurrency $base) == "1" ]]; then
     unset base
     echo "Invalid base currency"
     getBase
   fi
 }
+
 ## Checks base currency from the user and validates it with all the possible currency
 ## types available on the API (requires argument)
 checkBase()
 {
   base=$1
   base=$(echo $base | tr /a-z/ /A-Z/)
-  if [[ $(checkValidCurrency $base) == "1" ]];then
+  if [[ $(checkValidCurrency $base) == "1" ]]; then
     unset base
     echo "Invalid base currency"
     exit 1
@@ -80,7 +94,7 @@ getExchangeTo()
   echo -n "What currency to exchange to: "
   read -r exchangeTo
   exchangeTo=$(echo $exchangeTo | tr /a-z/ /A-Z/)
-  if [[ $(checkValidCurrency $exchangeTo) == "1" ]];then
+  if [[ $(checkValidCurrency $exchangeTo) == "1" ]]; then
     echo "Invalid exchange currency"
     unset exchangeTo
     getExchangeTo
@@ -93,7 +107,7 @@ checkExchangeTo()
 {
   exchangeTo=$1
   exchangeTo=$(echo $exchangeTo | tr /a-z/ /A-Z/)
-  if [[ $(checkValidCurrency $exchangeTo) == "1" ]];then
+  if [[ $(checkValidCurrency $exchangeTo) == "1" ]]; then
     echo "Invalid exchange currency"
     unset exchangeTo
     exit 1
@@ -129,37 +143,68 @@ checkAmount()
 
 checkInternet()
 {
-  httpGet google.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query google with a get request
+  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
 }
 
 ## Grabs the exchange rate and does the math for converting the currency
 convertCurrency()
 {
-  exchangeRate=$(httpGet "http://api.fixer.io/latest?base=$base&symbols=$exchangeTo" | grep -Eo "[0-9]*[.][0-9]*") > /dev/null
-  exchangeAmount=$(echo "$exchangeRate * $amount" | bc  )
-  echo
-  echo "========================="
-  echo "| $base to $exchangeTo"
-  echo "| Rate: $exchangeRate"
-  echo "| $base: $amount"
-  echo "| $exchangeTo: $exchangeAmount"
-  echo "========================="
+  trueBase=$base
+  trueTarget=$exchangeTo
+  peggedBase=$( peggedTo "$base" )
+  peggedTarget=$( peggedTo "$exchangeTo" )
+  coef1="1"
+  coef2="1"
+  if [[ "$peggedBase" =~ ^[A-Z]+:[0-9.]+$ ]]; then
+    trueBase=$(echo "$peggedBase" | grep -Eo "^[A-Z]*")
+    coef1=$(echo "$peggedBase" | grep -Eo "[0-9.]*$")
+  fi
+  if [[ "$peggedTarget" =~ ^[A-Z]+:[0-9.]+$ ]]; then
+    trueTarget=$(echo "$peggedTarget" | grep -Eo "^[A-Z]*")
+    coef2=$(echo "$peggedTarget" | grep -Eo "[0-9.]*$")
+  fi
+  if [[ "$trueBase" == "$exchangeTo" || "$base" == "$trueTarget" ]]; then
+    exchangeRate="1"
+  else
+    exchangeRate=$(httpGet "https://api.exchangeratesapi.io/latest?base=$trueBase" | grep -Eo "$trueTarget\":[0-9.]*" | grep -Eo "[0-9.]*") > /dev/null
+  fi
+  if ! command -v bc &>/dev/null; then
+    exchangeRate=$(echo "$exchangeRate" | grep -Eo "^[0-9]*" )
+    amount=$(echo "$amount" | grep -Eo "^[0-9]*" )
+    coef1=$(echo "$coef1" | grep -Eo "^[0-9]*" )
+    exchangeRate=$(( exchangeRate / coef1 ))
+    exchangeRate=$(( exchangeRate * coef2 ))
+    exchangeAmount=$(( exchangeRate * amount ))
+  else
+    exchangeRate=$( echo "scale=8; $exchangeRate / $coef1" | bc )
+    exchangeRate=$( echo "$exchangeRate * $coef2" | bc )
+    exchangeAmount=$( echo "$exchangeRate * $amount" | bc )
+  fi
+
+  cat <<EOF
+=========================
+| $base to $exchangeTo
+| Rate: $exchangeRate
+| $base: $amount
+| $exchangeTo: $exchangeAmount
+=========================
+EOF
 }
 
 update()
 {
   # Author: Alexander Epstein https://github.com/alexanderepstein
-  # Update utility version 1.2.0
+  # Update utility version 2.2.0
   # To test the tool enter in the defualt values that are in the examples for each variable
   repositoryName="Bash-Snippets" #Name of repostiory to be updated ex. Sandman-Lite
   githubUserName="alexanderepstein" #username that hosts the repostiory ex. alexanderepstein
   nameOfInstallFile="install.sh" # change this if the installer file has a different name be sure to include file extension if there is one
   latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option
 
-  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]];then
+  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
     echo "Error: update utility has not been configured correctly." >&2
     exit 1
-  elif [[ $latestVersion == "" ]];then
+  elif [[ $latestVersion == "" ]]; then
     echo "Error: no active internet connection" >&2
     exit 1
   else
@@ -167,16 +212,20 @@ update()
       echo "Version $latestVersion available"
       echo -n "Do you wish to update $repositoryName [Y/n]: "
       read -r answer
-      if [[ "$answer" == "Y" || "$answer" == "y" ]] ;then
-        cd  ~ || { echo 'Update Failed' ; exit 1 ; }
-        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName  ||  { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
-        git clone "https://github.com/$githubUserName/$repositoryName" || { echo "Couldn't download latest version" ; exit 1; }
-        cd $repositoryName ||  { echo 'Update Failed' ; exit 1 ;}
+      if [[ "$answer" == [Yy] ]]; then
+        cd ~ || { echo 'Update Failed'; exit 1; }
+        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update as sudo"; exit 1; } ; fi
+        echo -n "Downloading latest version of: $repositoryName."
+        git clone -q "https://github.com/$githubUserName/$repositoryName" && touch .BSnippetsHiddenFile || { echo "Failure!"; exit 1; } &
+        while [ ! -f .BSnippetsHiddenFile ]; do { echo -n "."; sleep 2; };done
+        rm -f .BSnippetsHiddenFile
+        echo "Success!"
+        cd $repositoryName || { echo 'Update Failed'; exit 1; }
         git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
         chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
-        rm -r -f $repositoryName ||  { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
+        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"; exit 1; }
       else
         exit 1
       fi
@@ -184,71 +233,69 @@ update()
       echo "$repositoryName is already the latest version"
     fi
   fi
-
 }
 
 
 usage()
 {
-  echo "Currency"
-  echo "Description: A realtime currency converter."
-  echo "   With no flags it will guide you through the currency exchange"
-  echo "Usage: currency or currency [flag] or currency [base] [exchangeTo] [amount]"
-  echo "  -u Update Bash-Snippet Tools"
-  echo "  -h Show the help"
-  echo "  -v Get the tool version"
-  echo "Supported Currencies:"
-  echo " _______________________"
-  echo "| AUD | BGN | BRL | CAD |"
-  echo "| CHF | CNY | CZK | DKK |"
-  echo "| EUR | GBP | HKD | HRK |"
-  echo "| HUF | IDR | ILS | INR |"
-  echo "| JPY | KRW | MXN | MYR |"
-  echo "| NOK | NZD | PHP | PLN |"
-  echo "| RON | RUB | SEK | SGD |"
-  echo "| THB | TRY | USD | ZAR |"
-  echo " _______________________"
-  echo "Examples:"
-  echo "  currency EUR USD 12.35"
-  echo "  currency"
+  cat <<EOF
+Currency
+Description: A realtime currency converter.
+   With no flags it will guide you through the currency exchange
+Usage: currency or currency [flag] or currency [base] [exchangeTo] [amount]
+  -u  Update Bash-Snippet Tools
+  -h  Show the help
+  -v  Get the tool version
+Supported Currencies:
+ ______________________________
+| AUD | BGN | BRL | CAD | ZAR |
+| CHF | CNY | CZK | DKK |     |
+| EUR | GBP | HKD | HRK |     |
+| HUF | ISK | IDR | ILS |     |
+| INR | JPY | KRW | MXN |     |
+| MYR | NOK | NZD | PHP |     |
+| PLN | RON | RUB | SEK |     |
+| SGD | THB | TRY | USD |     |
+ ______________________________
+Examples:
+  currency EUR USD 12.35
+  currency
+EOF
 }
 
 getConfiguredClient || exit 1
-checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+
 
 while getopts "uvh" opt; do
-  case $opt in
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      exit 1
-    ;;
-    h)
-      usage
-      exit 0
-    ;;
-    v)
-      echo "Version $currentVersion"
-      exit 0
-    ;;
-    u)
-      update
-      exit 0
-    ;;
-    :)
-      echo "Option -$OPTARG requires an argument." >&2
-      exit 1
-    ;;
+  case "$opt" in
+    \?) echo "Invalid option: -$OPTARG" >&2
+        exit 1
+        ;;
+    h)  usage
+        exit 0
+        ;;
+    v)  echo "Version $currentVersion"
+        exit 0
+        ;;
+    u)  checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+        update
+        exit 0
+        ;;
+    :)  echo "Option -$OPTARG requires an argument." >&2
+        exit 1
+        ;;
   esac
 done
 
 if [[ $# == 0 ]]; then
+  checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
   getBase # get base currency
   getExchangeTo # get exchange to currency
   getAmount # get the amount to be converted
   convertCurrency # grab the exhange rate and perform the conversion
   exit 0
 elif [[ $# == "1" ]]; then
-  if [[ $1 == "update" ]];then
+  if [[ $1 == "update" ]]; then
     update
   elif [[ $1 == "help" ]]; then
     usage
@@ -261,10 +308,14 @@ elif [[ $# == "2" ]]; then
   echo "Not a valid argument"
   usage
   exit 1
-elif [[ $# == "3" ]];then
+elif [[ $# == "3" ]]; then
+  checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
   checkBase $1
   checkExchangeTo $2
   checkAmount $3
   convertCurrency
   exit 0
+else
+  echo "Error: too many arguments."
 fi
+
